development:
  name: pin-workspace
  url: http://dev.workspace.2010.mindpin.com/ 
  master_url: http://dev.config-manager.2010.mindpin.com/
  git_repo_path: /root/mindpin_base/git_repo

test:
  name: pin-workspace
  url: http://dev.workspace.2010.mindpin.com/
  master_url: http://dev.config-manager.2010.mindpin.com/
  git_repo_path: /root/mindpin_base/git_repo

production:
  name: pin-workspace
  url: http://workspace.2010.mindpin.com/
  master_url: http://config-manager.2010.mindpin.com/
  git_repo_path: /web/2010/git_repo
