development:
  name: pin-workspace
  url: http://192.168.1.8:6006/
  master_url: http://192.168.1.8:6001/
  ui_url:  http://192.168.1.8:3000/

test:
  name: pin-workspace
  url: http://192.168.1.8:6006/
  master_url: http://192.168.1.8:6001/

production:
  name: pin-workspace
  url: http://192.168.1.8:6006/
  master_url: http://192.168.1.8:6001/