development:
  name: pin-workspace
  url: http://192.168.1.8:6006/
  master_url: http://192.168.1.8:3000/
  git_repo_path: /root/mindpin_base/git_repo

test:
  name: pin-workspace
  url: http://192.168.1.8:6006/
  master_url: http://192.168.1.8:3000/
  git_repo_path: /root/mindpin_base/git_repo

production:
  name: pin-workspace
  url: http://2010.mindpin.com/
  master_url: http://2010.mindpin.com/
  git_repo_path: /web/2010/git_repo
